ARG VERSION
# pg_dump and pg_restore come from this base image,
# based on the TimescaleDB version one wants
FROM postgres:${VERSION}-alpine

# Copy the Golang binaries from this official image,
# rather than installing manually
COPY --from=golang:rc-alpine /usr/local/go/ /usr/local/go/

LABEL maintainer="Sean McCarthy <sean.mccarthy@live.ca>"

RUN apk update && \
    # Install Python3 and pip to install the AWS CLI for AWS S3 access
    apk add --no-cache python3 py3-pip nano && \
    # Install AWS command line interface for S3 uploading
    pip3 install awscli six && \
    # Cleanup to reduce container size
    rm -rf /var/cache/apk/*

# Configure Go
ENV GOROOT /usr/local/go
ENV GOPATH /go
ENV PATH /usr/local/go/bin:$PATH

RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin

# Download and build the ts-dump and ts-restore Golang packages
RUN go get -u github.com/timescale/timescaledb-backup/ || true && \
    # cd to the download directory
    cd /go/pkg/mod/github.com/timescale/timescaledb-backup@v0.0.0-20210107191149-ff6031c44f8b && \
    # Replace ts-dump-restore reference with timescaledb-backup in the go.mod file
    sed -i 's/github.com\/timescale\/ts-dump-restore/github.com\/timescale\/timescaledb-backup/g' go.mod && \
    # Build ts-dump first
    cd cmd/ts-dump && \
    go mod tidy && \
    go build -o /usr/local/go/bin/ts-dump && \
    # Build ts-restore second
    cd ../ts-restore && \
    go mod tidy && \
    go build -o /usr/local/go/bin/ts-restore

# Set some default environment variables
# We'll override these with Docker-Compose and in the .env file
ENV POSTGRES_DATABASE **None**
ENV POSTGRES_HOST **None**
ENV POSTGRES_PORT **None**
ENV POSTGRES_USER **None**
ENV POSTGRES_PASSWORD **None**
ENV POSTGRES_BACKUP_EXTRA_OPTS ''
ENV POSTGRES_RESTORE_EXTRA_OPTS ''
ENV AWS_ACCESS_KEY_ID **None**
ENV AWS_SECRET_ACCESS_KEY **None**
ENV S3_BUCKET **None**
ENV AWS_DEFAULT_REGION **None**
ENV S3_ENDPOINT **None**
ENV S3_S3V4 no
ENV SCHEDULE **None**
ENV EDITOR nano

# Add a few more files to the container
# backup.sh actually runs the backup, and then uploads it to an AWS S3 bucket
COPY backup.sh backup.sh
COPY backup_ts.sh backup_ts.sh
# restore.sh will restore a database from a backup file,
# which has been downloaded from AWS S3 and renamed "postgres.bak"
COPY restore.sh restore.sh
COPY restore_ts.sh restore_ts.sh

# run_or_schedule_backup.sh schedules the backup with cron
COPY run_or_schedule_backup.sh run_or_schedule_backup.sh

RUN chmod +x run_or_schedule_backup.sh && \
    chmod +x backup_ts.sh && \
    chmod +x restore_ts.sh