version: '3.8'
services:
  dev_container:
    volumes:
      # Mount the root folder that contains .git
      - ..:/workspace
    build:
      # context: where should docker-compose look for the Dockerfile?
      # i.e. either a path to a directory containing a Dockerfile, or a url to a git repository
      context: ..
      dockerfile: Dockerfile.dev
      args:
        VERSION: 13
    env_file: ../.env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
